language: node_js
node_js:
  - "lts/*"
before_script:
  - cp -Rf ispack/isfiles-unicode/* inno-setup
  - mkdir -p inno-setup/Languages
  - cp -f issrc/Files/Languages/Unofficial/* inno-setup/Languages
  - rm -rf inno-setup/Examples
  - npm install -g tfx-cli
script:
  - tfx extension create --manifest-globs vss-extension.json
deploy:
  provider: releases
  api_key:
    secure: "mwmDZAcYW/chZdfpHTtK2rnpx4Dzp9kjKLUTz/rHl3ukDTuXtiWoYDQ+qYBd8IwbKos2GC6RCnPaBqSN0MLLSy8mKs6ri2q4ISsnKH3ZAxYNCoTvOM8F07OO224/R5bJKM5fBgVeajaP1T2CAEKFZC39aFQbNiWnCMGrq/zoiR2VHek6ZhhBgh4T23AinKkUYXeFpMPr3APgXQMIMsAPJPnDerm6l+2YlJMc5wpP8PTUzwbTj7Bg8WbxxJxJQF+yk5nyIZ55oAbE7ynMhtPj+9kUatk9h9K3kvUzsRKdby5iJwtshTlIS1Dpbz9PaRVWmJwfOQ/SsnJWD5WGjmRu/kShmYRcByKo8hInKjb3t8G96BprIj7B5lShD1Tz+kUwmCVagQqSzd5Kts9r0ksQeNsBU9cKPl4slViq79hYIpCEr3FDbNaQrveQtqbWOQRuSsVhE9r4l0Ou7pREt54cJ8oFzN8F8xuUlWWUcouRzOkhC3neXK9EPRhwbmHStrS1Ic40bL9YhNFtLDNcfx2ttZjp1YeQv97itn4BmyITHhYrNkDuZdeKslb1ikchfRyk4FuiH1hOdpg7IWkxxC37dOuheOUlpEKFOvhqrDGUAHMIh8AeH0gfZUBKVUWld1Hem4Vh1fcq0wSS31LIo9aIS3jY4mFkZkjT8ewM1pVIlZE="
  file: echizenryoma.vsts-inno-setup-extension-*.vsix
  file_glob: true
  skip_cleanup: true
  on:
    tags: true